### ISSUE TITLE
cleanup what JS returns to shiny

### ISSUE THREAD

**Issue by MayaGans** [jdtrat/shinysurveys#14]
Right now JS returns a named list to shiny, and this can be hard to read/use downstream.
I'd be nice to turn this into a dataframe or list -- but where/how would this happen?

maybe I need to read this for a 4th time I think the answer is in here somewhere...... https://unleash-shiny.rinterface.com/shiny-input-system.html#custom-data-format

**Comment by jdtrat** [comment]
Can confirm that link should be read! 

Registered an input handler on package load in zzz.R file and then used `getType` method to return it appropriately.
