### ISSUE TITLE
Where is user data?

### ISSUE THREAD

**Issue by nklepeis** [jdtrat/shinysurveys#19]
Hi, Great package!  I apologize but I am not understanding something basic.   How do I programmatically access the user form data after they hit the "Submit" button?   Is it in a certain data frame object?

**Comment by jdtrat** [comment]
Hi, thank you! That's actually a great question, and I'm working on a robust and generalizable solution. Below is a toy example that should get you started, but please note you may need to modify it depending on your question set. For example, if your survey has both numeric and text inputs, when you call `map_df`, you would need to convert all of them to the same type.

```r
library(shiny)
library(shinysurveys)
library(purr)

df <- data.frame(question = "What is your favorite food?",
                 option = "Your Answer",
                 input_type = "text",
                 input_id = "favorite_food",
                 dependence = NA,
                 dependence_value = NA,
                 required = F)

ui <- fluidPage(
  surveyOutput(df)
)

server <- function(input, output, session) {
  renderSurvey(df)
  
  # On submit, let's print the responses
  observeEvent(input$submit, {
    
    # Create a dataframe where the subject ID is equal to the userID
    # as set in the HTML path. For more details, on the user ID see
    # https://www.jdtrat.com/packages/shinysurveys/#advanced-surveys
    responses <- data.frame(subject_id = input$userID,
                            # Create a question indicator as just the input ID
                            question = df$input_id,
                            # Get the user responses for all input questions.
                            response = purrr::map_df(df$input_id,
                                                     ~ list(response = input[[.x]])))
  
    # Could also write responses to csv or save to cloud storage, etc...
    print(responses)
      
  })
  
}

shinyApp(ui, server)
```

**Comment by nklepeis** [comment]
OK thanks!   That gets me on track :)

**Comment by Benmoshe49** [comment]
Hi 

Thanks fo this useful package
Your code not seems to work @jdtrat 
@nklepeis Can you share youre code if you find a solution ? thanks 

Have a good day !

**Comment by jdtrat** [comment]
Hi! Can you provide a reprex? The above code works on my machine. I do see that I misspelled the `purrr` package when calling it on the second line, however. Maybe that's the issue for you?

**Comment by Benmoshe49** [comment]
Thanks it's finally work in my own machine. The problem come from the R versions maybe.

Is it possible to initialize the suvevey when button submit is clicked ?

Thanks

**Comment by jdtrat** [comment]
When you say "initialize", do you mean have the survey reset when you click the submit button?

**Comment by Benmoshe49** [comment]
Yes exactly reseting survey questions (something similar to shinyjs::reset())

**Comment by jdtrat** [comment]
@Benmoshe you should be able to use`shinyjs`, or custom JavaScript, to do that. If you want to create a separate issue, I'm happy to look into adding support for that.

**Comment by jdtrat** [comment]
@nklepeis (and @Benmoshe49), I just added support for a function `get_survey_data()` that should aggregate all responses into a tidy data frame. It will exclude any questions that were not shown (because they are dependencies). Would you mind giving it a try and seeing if it works for you? 

Here's an example:

```r

library(shiny)
#remotes::install_github("jdtrat/shinysurveys@extend-shinysurveys")
library(shinysurveys)

df <- data.frame(
  question = c("What's your favorite food?", rep("Do you like SunButter®", 2),
               "Where do you live?", "What is the temperature where you are?"),
  option = c("Sushi", "Yes", "No", "North Carolina", "79"),
  input_type = c("text", rep("y/n", 2), "text", "numeric"),
  input_id = c("favorite_food", rep("sunbutter", 2), "location", "temperature"),
  dependence = c(NA, "favorite_food", "favorite_food", NA, NA),
  dependence_value = c(NA, "Sushi", "Sushi", NA, NA),
  required = FALSE
)

ui <- fluidPage(
  surveyOutput(df, 
               survey_title = "{shinysurveys} Automatic Response Aggregation Example",
               survey_description = "The function `get_survey_data()` takes into account dependencies, 
               and will only include questions that participants saw when aggregating responses."
               )
)

server <- function(input, output, session) {
  renderSurvey()
  
  observeEvent(input$submit, {
    print(get_survey_data())
  })
}

shinyApp(ui, server)

```

**Comment by jdtrat** [comment]
Hi! I'm getting ready to launch v0.2.0 of shinysurveys, so if you have any feedback, please let me know ASAP!

**Comment by JuneKay92** [comment]
@jdtrat @mostafa790 Could you tell me what you mean by a problem with the R versions caused the code not to run?  I'm trying to use the `getSurveyData()` function with the latest release of the package, but I get an error with your simple example stating `Error in : Must use single string to index into reactivevalues.`  Even if I add in a reactive value, I get the same error.  Please and Thank you!

**Comment by jdtrat** [comment]
Hi @JuneKay92! Sorry you're having trouble with `getSurveyData()`. I haven't seen the error you described before. Would you be able to include a [reprex](reprex.tidyverse.org) so I can see what's going on?

**Comment by JuneKay92** [comment]
```
library(shiny)
library(shinysurveys)

df <- data.frame(question = "What is your favorite food?",
                 option = "Your Answer",
                 input_type = "text",
                 input_id = "favorite_food",
                 dependence = NA,
                 dependence_value = NA,
                 required = F)

ui <- fluidPage(
  surveyOutput(df,
               survey_title = "Hello, World!"
               )

server <- function(input, output, session) {
  renderSurvey()
  
  # observeEvent(input$submit, {
  #   # showModal(modalDialog(
  #   #   title = "Congrats, you completed your first shinysurvey!",
  #   #   "You can customize what actions happen when a user finishes a survey using input$submit."
  #   # ))
  #   print(shinysurveys::getSurveyData())
  # })
  
  observeEvent(input$submit, {
    response_data <- getSurveyData()
    print(response_data)
  })
}

shinyApp(ui, server)
```

This is your basic example from the vignette on `getSurveyData()` [https://shinysurveys.jdtrat.com/articles/get-survey-data.html](url).  For some reason the app won't start and gives me the above error.  Further testing I've done found that it works with the `teaching_r_questions` data frame included with the package but not a custom data frame.  I can't figure out why

**Comment by jdtrat** [comment]
🤔 hmm... could you run `sessioninfo::session_info()` for me, please? The code from the vignette on my machine. What R version are you using? shiny version?

**Comment by JuneKay92** [comment]
R 3.6.2 (which I know is out of date now) and shiny 1.6.0.

I have been able to get this function working only with tibbles, not as a data frame.  Maybe it's something to check, if it's not just me being on older versions

**Comment by jdtrat** [comment]
What version of `tibble` are you using?

**Comment by jdtrat** [comment]
Doing some maintenance and am closing the issue. If you have any other questions/feature requests, please feel free to reopen (if related) or create a new issue.
