### ISSUE TITLE
Please allow for "any" in showDependence(), arg dependence_value 

### ISSUE THREAD

**Issue by ClaudiuPapasteri** [jdtrat/shinysurveys#31]
First of all, thank you for the wonderful package. I am experimenting a lot with it and it works well in simplifying survey creation in Shiny. 
This is more of a simple feature request. Dependence should work both with specific values (the way dependence_value argument works now) and with any user-supplied value. 

Thanks again.

**Comment by jdtrat** [comment]
Thank you! Could you explain what you mean a little more? I'm not sure I follow what feature you would like. Would you like to be able to show a dependent manually, i.e. call `showDependence(id = "some-question")`?

**Comment by ClaudiuPapasteri** [comment]
No, it's actually way simpler. I am not even completely sure you can't do it with the current implementation. The basic idea would be to have a dependence to a question and any response as opposed to a specific response/value triggering it. From a design perspective, it would be great if this was managed with only the "dependence" argument, while "dependence_value" could be left NA. So setting dependence = "question1" would set the dependence on question1 regardless of the specific user response, any user response should trigger it. I know this could be harder to implement for items that have a default value.

**Comment by jdtrat** [comment]
Hmmm, I don't think this would require dependencies but a multipaged survey? You could have the parent question on one page and the 'dependent' on the next. [ Here's a blog post](https://www.jdtrat.com/blog/multi-paged-shinysurvey/) on creating a multipaged survey. Does that help?

**Comment by jdtrat** [comment]
@ClaudiuPapasteri Doing some maintenance and am closing this. If you have any other comments/feature requests, please feel free to reopen (if related) or create a new issue.
