### ISSUE TITLE
Formatting Instructions

### ISSUE THREAD

**Issue by CurtisPetersen** [jdtrat/shinysurveys#36]
Great package!

Is there a straightforward way to pass formatting to instructions input_type? In this example I've added HTML coding into the question text for an input_type of instructions without the desired effect.

![Screen Shot 2021-09-03 at 3 49 58 PM](https://user-images.githubusercontent.com/13002038/132072320-04544b11-37d5-45b0-adcc-df00ff162ef8.png)

**Comment by jdtrat** [comment]
Thanks, Curtis! 

I've been thinking about this feature for a while -- I just added support for markdown syntax with the instructions blocks. Below is an example and preview. Please let me know if you have any questions!

```r
library(shiny)
# remotes::install_github("jdtrat/shinysurveys")
library(shinysurveys)
instructions_df <- data.frame(question = c("This is an instructions block! It now supports markdown syntax. For example:
                                           To **bold**, you can use double asterisks (\\*\\*). *Italicize* with single asterisks (\\*).", 
                                           "# Use a \\# for titles
                                           #### \\#\\#\\#\\# for smaller titles
                                           Here's some `inline code` because we can!
                                           ",
                                           "Do you like this new formatting feature?"),
                option = c(NA, NA, "Yes!"),
                input_type = c("instructions", "instructions", "text"),
                input_id = c("markdown_instructions", "markdown_instructions2", "like_new_feature"),
                dependence = NA,
                dependence_value = NA,
                required = F)

ui <- fluidPage(
    surveyOutput(instructions_df, 
                            survey_title = "Markdown Support for 'Instructions' Blocks")
)

server <- function(input, output, session) {
  renderSurvey()
}

shinyApp(ui, server)
```


![Screen Shot 2021-09-04 at 3 58 31 PM](https://user-images.githubusercontent.com/51417262/132106561-bae8ad5c-2619-405b-b44b-6ea33c80e089.png)

**Comment by CurtisPetersen** [comment]
This is a great addition!

Thank you!

**Comment by CurtisPetersen** [comment]
After testing looks like I'm getting an error. 

`> remotes::install_github("jdtrat/shinysurveys")
Skipping install of 'shinysurveys' from a github remote, the SHA1 (3a6e1da7) has not changed since last install.
  Use `force = TRUE` to force installation
> runApp('Desktop/Tests/New_survey/New_survey')
Warning in `[<-.factor`(`*tmp*`, is.na(df[["option"]]), value = "Placeholder") :
  invalid factor level, NA generated
Error in glue::trim(mds) : 
  STRING_ELT() can only be applied to a 'character vector', not a 'integer'
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X  11.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinysurveys_0.2.0.9000 shiny_1.6.0            

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7           withr_2.4.2          digest_0.6.27        later_1.3.0          commonmark_1.7       mime_0.11           
 [7] R6_2.5.1             lifecycle_1.0.0      xtable_1.8-4         magrittr_2.0.1       rlang_0.4.11.9001    cli_3.0.1           
[13] curl_4.3.2           remotes_2.4.0        promises_1.2.0.1     ellipsis_0.3.2       tools_3.6.2          glue_1.4.2          
[19] httpuv_1.6.2         fastmap_1.1.0        compiler_3.6.2       htmltools_0.5.2.9000
> `

It looks like a column is not being considered a character. Updating the example with a mutate_all(as.character) fixes the issue. There might be a more comprehensive fix. Here is the updated code:

`library(shiny)
# remotes::install_github("jdtrat/shinysurveys")
library(shinysurveys)
library(tidyverse)

instructions_df <- data.frame(question = c("This is an instructions block! It now supports markdown syntax. For example:
                                           To **bold**, you can use double asterisks (\\*\\*). *Italicize* with single asterisks (\\*).", 
                                           "# Use a \\# for titles
                                           #### \\#\\#\\#\\# for smaller titles
                                           Here's some `inline code` because we can!
                                           ",
                                           "Do you like this new formatting feature?"),
                              option = c(NA, NA, "Yes!"),
                              input_type = c("instructions", "instructions", "text"),
                              input_id = c("markdown_instructions", "markdown_instructions2", "like_new_feature"),
                              dependence = NA,
                              dependence_value = NA,
                              required = F) %>%
    mutate_all(as.character)

ui <- fluidPage(
    surveyOutput(instructions_df, 
                 survey_title = "Markdown Support for 'Instructions' Blocks")
)

server <- function(input, output, session) {
    renderSurvey()
}

shinyApp(ui, server)`
