### ISSUE TITLE
How to make shinysurveys app to reset all values and return to initial page after clicking dismiss

### ISSUE THREAD

**Issue by covid19ec** [jdtrat/shinysurveys#42]
Hi all. I am working in shinysurveys and I would like to know if there is any option that after filling all the questions and submitting, in the final message that appear after click the dismiss, can it be possible to return to first page and reset all the questions? The code I have is next:

```
library(shiny)
library(shinysurveys)

df <- data.frame(question = c("What is your favorite food?","Do you love it?","Do you love it?"),
                 option = c("Your Answer","Yes","No"),
                 input_type = c("text","mc","mc"),
                 input_id = c("favorite_food","love_it","love_it"),
                 dependence = NA,
                 dependence_value = NA,
                 required = F,page=c(1,2,2))

ui <- fluidPage(
  surveyOutput(df = df,
               survey_title = "Hello, World!",
               survey_description = "Welcome! This is a demo survey showing off the {shinysurveys} package.")
)

server <- function(input, output, session) {
  renderSurvey()
  
  observeEvent(input$submit, {
    showModal(modalDialog(
      title = "Congrats, you completed your first shinysurvey!",
      "Click on Dismiss"
    ))
  })
}

shinyApp(ui, server)
```

The app has two pages, so in the final page after submit I got this:

![imagen](https://user-images.githubusercontent.com/84138212/150128140-042569b6-1c4a-409b-b4e3-b81896076ffe.png)

After clicking on dismiss, is possible to reset all the questions and return to initial page?

Many thanks!

**Comment by jdtrat** [comment]
Hey! Great question. I think replacing your server with this should do the trick. This will reset your Shiny session (clearing all existing input). That shouldn't be a problem as long as you're saving the responses before the modal is dismissed. You can read more about the `session` object and methods[ here](https://shiny.rstudio.com/reference/shiny/1.6.0/session.html) or other alternatives for resetting inputs/session on this [SO post](https://stackoverflow.com/questions/25062422/restart-shiny-session).

```r
server <- function(input, output, session) {
  renderSurvey()
  
  observeEvent(input$submit, {
    showModal(modalDialog(
      title = "Congrats, you completed your first shinysurvey!",
      "Click on Dismiss",
      footer = actionButton("dismiss", "Dismiss!"))
    )
  })
  
  observeEvent(input$dismiss, session$reload())
  
}

shinyApp(ui, server)
```

**Comment by covid19ec** [comment]
Many thanks this solved the issue!
